name: Find Secrets
# Controls when the workflow will run
on:
  [push, pull_request]
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  startup:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: max/secret-scan@master
        continue-on-error: true
